### ISSUE TITLE
一些代码规范上的建议。

### ISSUE THREAD

**Issue by magicsilly** [BDFFZI/BDXKEngine#1]
希望把书写规范降级到c++14，现在的c++20不方便普及。第二个问题是不要用过于靠前的语法规则，这样很多人都用不了，避免很多问题。

**Comment by BDFFZI** [comment]
## 使用C++20的原因
使用C++20是因为多了很多便利性的功能，比如要从vector中删除一个元素，C++20有专门的std::erase函数，调用起来非常简便，而旧版本就得写的很罗嗦。
如果要在旧版本C++中处理类似的情况，我就必须要自己写一些工具库，或者用第三方的库，这便与我的开发规则“不要造标准库的轮子”存在冲突。
看似低等级C++中的函数普及性比较高，但这样实际上是把部分功能的学习成本转到了第三方库或自研上，我认为学习第三方库的风险比学习新版本C++要高的多。

## 使用C++20的风险
考虑到成本问题，以及未来工作中可能遇见的情况，我不会完全选择造轮子这条路，而是选择性的会使用一些市面上主流的第三方库。但这些库不少都是早期产品，有时会存在不兼容C++20新语法的问题。
不过幸运的是正是因为他们足够流行，所以会有很多人去主动完善这些缺陷。我之前遇到过因版本兼容性而无法使用的库，但他们的issues里都会有解决办法。另外最近我在接入PhysX，使用C++20后也是可以通过编译的。
所以这一风险影响不大

## 另一个决定性的原因
这个游戏引擎我当然希望它能发展壮大，但目前也只能放在幻想中，最现实的情况是它的受众对象只有我自己，我用它更多的也只是学习目的。而且再过段时间我可能就要停更了，所以我目前也没有太多时间处理这个。
目前我更希望能减少无用轮子的开发并能更多的学习标准库，所以我要用C++20，也不会太多考虑普及性的问题

## 关于过于靠前的语法规则
“过于靠前的语法规则”这句我不是太懂意思。
1. 如果是指用一些新式语法写代码，比如我之前提到的删除元素的例子，那因此产生理解障碍正是我的目的之一，因为他们都是标准库的内容，是需要的学习的东西。
2. 如果是指编码规范不符合C++标准，这是因为我之前一直在用C#，结果就把这些习惯带过来了。而且我最开始的目的是尽可能模仿Unity，所以编码环境也有意学习C#的一套。

**Comment by magicsilly** [comment]
我不希望你把它当作一个幻想，而是梦想。因为这样的框架性项目，需要的是忍耐和坚持。我看了你的全部代码，整体上都是不错的，不要那么轻易放弃它。
对于c++来说，更多的是方便参与其中的人，如果语法规则太新，就不方便其他人参与。

大佬先帮我如何解决问题，

**Comment by magicsilly** [comment]
![QQ截图20221223201805](https://user-images.githubusercontent.com/10555882/209335127-3c1975b3-2737-4578-bd86-c58da225246b.png)

**Comment by BDFFZI** [comment]
看样子必须要改c++版本了，但你也看到报错这么多得改很久。但升级到vs2022应该是相当简单的事，你之前说你必须要用vs2017是为什么？

**Comment by BDFFZI** [comment]
长时间不回复我就先关闭了，但C++我依旧会坚持使用20的版本，很抱歉。
